import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/HomeNew.module.scss'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let [inputValue, setInputValue] = useState('');
  function handleInput(value: DOMAttributes<HTMLInputElement>.onInput?: FormEventHandler<HTMLInputElement> | undefined) {
    console.log(value);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <div className={styles.search}>
          <input type="search" maxLength={250} value={inputValue} onInput={handleInput} />
        </div>
      </main>
    </>
  )
}
